In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score


## Loading Data

In [3]:
X_flooded_lbp = np.zeros((461, 65536), dtype=np.uint8)
X_non_flooded_lbp = np.zeros((461, 65536), dtype=np.uint8)
X_flooded_hog = np.zeros((461, 142884), dtype=np.uint8)
X_non_flooded_hog = np.zeros((461, 142884), dtype=np.uint8)
X_flooded_glcm = np.zeros((461, 10), dtype=np.uint8)
X_non_flooded_glcm = np.zeros((461, 10), dtype=np.uint8)

X_flooded_lbp = np.load('../dataset/dataset/flooded_features_lbp.npy')
print(X_flooded_lbp.shape)
X_non_flooded_lbp = np.load('../dataset/dataset/non-flooded_features_lbp.npy')
print(X_non_flooded_lbp.shape)
X_flooded_hog = np.load('../dataset/dataset/flooded_features_hog.npy')
print(X_flooded_hog.shape)
X_non_flooded_hog = np.load('../dataset/dataset/non-flooded_features_hog.npy')
print(X_non_flooded_hog.shape)
X_flooded_glcm = np.load('../dataset/dataset/flooded_features_glcm.npy')
print(X_flooded_glcm.shape)
X_non_flooded_glcm = np.load('../dataset/dataset/non-flooded_features_glcm.npy')
print(X_non_flooded_glcm.shape)

(461, 65536)
(461, 65536)
(461, 142884)
(461, 142884)
(461, 10)
(461, 10)


## Models with lbp only 

In [11]:
y_flooded_lbp = np.ones((X_flooded_lbp.shape[0], 1))
y_non_flooded_lbp = np.zeros((X_non_flooded_lbp.shape[0], 1))
X = np.concatenate((X_flooded_lbp, X_non_flooded_lbp), axis=0)
y = np.concatenate((y_flooded_lbp, y_non_flooded_lbp), axis=0)

In [12]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# train model
model = LogisticRegression()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
# print confusion matrix
print(confusion_matrix(y_test, y_pred))

c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0       0.73      0.89      0.80        87
         1.0       0.88      0.71      0.79        98

    accuracy                           0.79       185
   macro avg       0.80      0.80      0.79       185
weighted avg       0.81      0.79      0.79       185

Omission error: 28.57
Commission error: 12.50
[[77 10]
 [28 70]]


c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
# use random forest
model = RandomForestClassifier()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_13316\4034023628.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


              precision    recall  f1-score   support

         0.0       0.74      0.85      0.79        87
         1.0       0.85      0.73      0.79        98

    accuracy                           0.79       185
   macro avg       0.79      0.79      0.79       185
weighted avg       0.80      0.79      0.79       185

Omission error: 26.53
Commission error: 15.29
[[74 13]
 [26 72]]


In [15]:
# use naive bayes
model = GaussianNB()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))

c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0       0.82      0.86      0.84        87
         1.0       0.87      0.83      0.85        98

    accuracy                           0.84       185
   macro avg       0.84      0.84      0.84       185
weighted avg       0.84      0.84      0.84       185

Omission error: 17.35
Commission error: 12.90
[[75 12]
 [17 81]]


## Models with Histogram

In [16]:
y_flooded_hog = np.ones((X_flooded_hog.shape[0], 1))
y_non_flooded_hog= np.zeros((X_non_flooded_hog.shape[0], 1))
X = np.concatenate((X_flooded_hog, X_non_flooded_hog), axis=0)
y = np.concatenate((y_flooded_hog, y_non_flooded_hog), axis=0)

In [17]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# train model
model = LogisticRegression()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
# print confusion matrix
print(confusion_matrix(y_test, y_pred))

c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


              precision    recall  f1-score   support

         0.0       0.67      0.84      0.74        87
         1.0       0.82      0.63      0.71        98

    accuracy                           0.73       185
   macro avg       0.74      0.74      0.73       185
weighted avg       0.75      0.73      0.73       185

Omission error: 36.73
Commission error: 18.42
[[73 14]
 [36 62]]


In [19]:
# use random forest
model = RandomForestClassifier()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_13316\4034023628.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


              precision    recall  f1-score   support

         0.0       0.80      0.76      0.78        87
         1.0       0.80      0.84      0.82        98

    accuracy                           0.80       185
   macro avg       0.80      0.80      0.80       185
weighted avg       0.80      0.80      0.80       185

Omission error: 16.33
Commission error: 20.39
[[66 21]
 [16 82]]


In [20]:
# use naive bayes
model = GaussianNB()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))

c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0       0.72      0.80      0.76        87
         1.0       0.81      0.72      0.76        98

    accuracy                           0.76       185
   macro avg       0.76      0.76      0.76       185
weighted avg       0.77      0.76      0.76       185

Omission error: 27.55
Commission error: 19.32
[[70 17]
 [27 71]]


## Models with Histo and lbp

In [21]:
X_lbp = np.concatenate((X_flooded_lbp, X_non_flooded_lbp), axis=0)
X_hog = np.concatenate((X_flooded_hog, X_non_flooded_hog), axis=0)
X = np.concatenate((X_lbp, X_hog), axis=1)
y = np.concatenate((y_flooded_lbp, y_non_flooded_lbp), axis=0)
print(X.shape)
print(y.shape)
# 142884 +65536 


(922, 208420)
(922, 1)


In [22]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
# train model
model = LogisticRegression()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
# print confusion matrix
print(confusion_matrix(y_test, y_pred))

c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


              precision    recall  f1-score   support

         0.0       0.73      0.89      0.80        87
         1.0       0.88      0.71      0.79        98

    accuracy                           0.79       185
   macro avg       0.80      0.80      0.79       185
weighted avg       0.81      0.79      0.79       185

Omission error: 28.57
Commission error: 12.50
[[77 10]
 [28 70]]


In [24]:
# use random forest
model = RandomForestClassifier()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_13316\4034023628.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


              precision    recall  f1-score   support

         0.0       0.81      0.74      0.77        87
         1.0       0.78      0.85      0.81        98

    accuracy                           0.79       185
   macro avg       0.80      0.79      0.79       185
weighted avg       0.80      0.79      0.79       185

Omission error: 15.31
Commission error: 21.70
[[64 23]
 [15 83]]


In [25]:
# use naive bayes
model = GaussianNB()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))

c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0       0.73      0.80      0.77        87
         1.0       0.81      0.73      0.77        98

    accuracy                           0.77       185
   macro avg       0.77      0.77      0.77       185
weighted avg       0.77      0.77      0.77       185

Omission error: 26.53
Commission error: 19.10
[[70 17]
 [26 72]]


## Models with GLCM (ALL)

In [4]:
y_flooded_glcm = np.ones((X_flooded_glcm.shape[0], 1))
y_non_flooded_glcm = np.zeros((X_non_flooded_glcm.shape[0], 1))
X = np.concatenate((X_flooded_glcm, X_non_flooded_glcm), axis=0)
y = np.concatenate((y_flooded_glcm, y_non_flooded_glcm), axis=0)

In [5]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
# train model
model = LogisticRegression()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
# print confusion matrix
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.76      0.76      0.76        87
         1.0       0.79      0.79      0.79        98

    accuracy                           0.77       185
   macro avg       0.77      0.77      0.77       185
weighted avg       0.77      0.77      0.77       185

Omission error: 21.43
Commission error: 21.43
[[66 21]
 [21 77]]


c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
# use random forest
model = RandomForestClassifier()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))


C:\Users\lenovo\AppData\Local\Temp\ipykernel_31208\3639885457.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)


              precision    recall  f1-score   support

         0.0       0.83      0.84      0.83        87
         1.0       0.86      0.85      0.85        98

    accuracy                           0.84       185
   macro avg       0.84      0.84      0.84       185
weighted avg       0.84      0.84      0.84       185

Omission error: 15.31
Commission error: 14.43
[[73 14]
 [15 83]]


In [8]:
# use naive bayes
model = GaussianNB()
model.fit(X_train, y_train)
# test model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('Omission error: %.2f' % ((1-recall_score(y_test, y_pred))*100))
print('Commission error: %.2f' % ((1-precision_score(y_test, y_pred))*100))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

         0.0       0.79      0.78      0.79        87
         1.0       0.81      0.82      0.81        98

    accuracy                           0.80       185
   macro avg       0.80      0.80      0.80       185
weighted avg       0.80      0.80      0.80       185

Omission error: 18.37
Commission error: 19.19
[[68 19]
 [18 80]]


c:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
